# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=140)),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=12)),
                ('num_exp', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('modular', models.BooleanField()),
                ('inmigrante', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(blank=True)),
                ('conv', models.BooleanField()),
                ('apro', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('horas_semana', models.IntegerField()),
                ('horas_anuales', models.IntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Modulo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='modulos',
            field=models.ManyToManyField(to='bd.Modulo'),
        ),
    ]
