# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_auto_20170110_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='num_exp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
