# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_auto_20170110_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convalidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Alumno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='ModulosAprobados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Alumno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Modulo')),
            ],
        ),
    ]
