# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_auto_20170110_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='modulos',
        ),
    ]
