# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_remove_alumno_modulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convalidacion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='convalidacion',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='modulosaprobados',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='modulosaprobados',
            name='modulo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='convalidaciones',
            field=models.ManyToManyField(related_name='convalidaciones', to='bd.Modulo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.ManyToManyField(related_name='matriculas', to='bd.Modulo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='mods_aprobados',
            field=models.ManyToManyField(related_name='aprobados', to='bd.Modulo'),
        ),
        migrations.DeleteModel(
            name='Convalidacion',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='ModulosAprobados',
        ),
    ]
