# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_auto_20170110_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='convalidaciones',
            field=models.ManyToManyField(blank=True, related_name='convalidaciones', to='bd.Modulo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='mods_aprobados',
            field=models.ManyToManyField(blank=True, related_name='aprobados', to='bd.Modulo'),
        ),
    ]
