# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_auto_20170110_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='repetidor',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
