# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0011_alumno_emancipada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
