# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_auto_20170110_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dir_postal',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tlf_urgencia_1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tlf_urgencia_2',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
