# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0015_calificacion_eval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='eval',
            new_name='ev',
        ),
    ]
