# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0016_auto_20170110_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
