# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0018_auto_20170110_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='modulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bd.Modulo'),
            preserve_default=False,
        ),
    ]
