# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0019_calificacion_modulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='calificacion',
            name='sin_matricula',
            field=models.NullBooleanField(),
        ),
    ]
